### ISSUE TITLE
Allow logging in with different devices at the same time

### ISSUE THREAD

**Issue by iijat** [iijat/nip05.social#3]
Currently, it is not possible to be logged in with different devices (or Browsers) at the same time. If you are logged in with one device, the other session is invalidated.

It should be possible to be logged in with different devices.

**Comment by ChrisAtIijat** [comment]
Currently, it is not possible to be logged in with different devices (or Browsers) at the same time. If you are logged in with one device, the other session is invalidated.

It should be possible to be logged in with different devices.

**Comment by iijat** [comment]
Implemented.
